# .github/workflows/deploy.yml

name: deploy
on:
  workflow_dispatch
#    branches:
#      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npx @serverless/cloud test
      - run: npx @serverless/cloud deploy prod
